system:
    default:
        css:
            files:
            # "external" fundation
                - '@eZPlatformUIAssetsBundle/Resources/public/vendors/pure/base-context-min.css'
                - '@eZPlatformUIAssetsBundle/Resources/public/vendors/pure/grids-min.css'
                - '@eZPlatformUIAssetsBundle/Resources/public/vendors/pure/buttons-min.css'
                - '@eZPlatformUIAssetsBundle/Resources/public/vendors/pure/tables-min.css'
            # layout stylesheets
                - '@eZPlatformUIBundle/Resources/public/css/layout.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/navigationhub.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/universaldiscovery.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/tree.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/loginform.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/contentedit.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/locationview.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/rawcontent.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/field.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/view/user.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/view/author.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/view/maplocation.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/view/selection.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/view/keyword.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/contenteditform.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/bar.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/discoverybar.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/contenttypeselector.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/actions/tree.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/actions/button.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/actions/preview.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/actions/create-content.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/editpreview.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fieldedit.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/error.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/asynchronous.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/checkbox.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/textline.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/keyword.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/textblock.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/xmltext.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/emailaddress.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/url.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/float.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/integer.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/maplocation.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/author.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/binarybase.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/image.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/media.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/binaryfile.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/selection.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/time.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/date.css'
                - '@eZPlatformUIBundle/Resources/public/css/views/fields/edit/dateandtime.css'
                - '@eZPlatformUIBundle/Resources/public/css/modules/tabs.css'
                - '@eZPlatformUIBundle/Resources/public/css/modules/page-header.css'
                - '@eZPlatformUIBundle/Resources/public/css/modules/serverside-content.css'
                - '@eZPlatformUIBundle/Resources/public/css/modules/selection-filter.css'
                - '@eZPlatformUIBundle/Resources/public/css/modules/button.css'
                - '@eZPlatformUIBundle/Resources/public/css/modules/table-data.css'
                - '@eZPlatformUIBundle/Resources/public/css/modules/breadcrumbs.css'
                - '@eZPlatformUIBundle/Resources/public/css/modules/yui-calendar.css'
            # theme stylesheets
                - '@eZPlatformUIBundle/Resources/public/css/theme/app.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/error.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/loginform.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/bar.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/universaldiscovery.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/tree.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/discoverybar.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/contenttypeselector.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/actions/tree.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/actions/button.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/actions/preview.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/actions/create-content.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/dashboard.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/serverside.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/navigationhub.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/locationview.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/rawcontent.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/asynchronous.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/field.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/view/url.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/view/binaryfile.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/view/maplocation.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/view/xmltext.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/contentedit.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/contenteditform.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/editpreview.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fieldedit.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/view/keyword.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/edit/maplocation.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/edit/author.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/edit/selection.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/edit/binarybase.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/edit/image.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/edit/media.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/edit/binaryfile.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/views/fields/edit/date.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/modules/tabs.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/modules/page-header.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/modules/serverside-content.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/modules/selection-filter.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/modules/button.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/modules/selection-table.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/modules/breadcrumbs.css'
                - '@eZPlatformUIBundle/Resources/public/css/theme/modules/yui-calendar.css'
