system:
    default:
        css:
            files:
            # "external" fundation
                - 'bundles/ezplatformuiassets/vendors/pure/base-context-min.css'
                - 'bundles/ezplatformuiassets/vendors/pure/grids-min.css'
                - 'bundles/ezplatformuiassets/vendors/pure/buttons-min.css'
                - 'bundles/ezplatformuiassets/vendors/pure/tables-min.css'
                - 'bundles/ezplatformuiassets/vendors/pure/forms-min.css'
                - 'bundles/ezplatformuiassets/vendors/flag-icon-css/css/flag-icon.min.css'
            # "fork" of alloyeditor CSS produced by `grunt alloy-css`
                - 'bundles/ezplatformui/css/external/alloy-editor-ez.css'
            # layout stylesheets
                - 'bundles/ezplatformui/css/layout.css'
                - 'bundles/ezplatformui/css/views/navigationhub.css'
                - 'bundles/ezplatformui/css/views/confirmbox.css'
                - 'bundles/ezplatformui/css/views/languageselectionbox.css'
                - 'bundles/ezplatformui/css/views/notificationhub.css'
                - 'bundles/ezplatformui/css/views/notification.css'
                - 'bundles/ezplatformui/css/views/universaldiscovery.css'
                - 'bundles/ezplatformui/css/views/universaldiscovery/browse.css'
                - 'bundles/ezplatformui/css/views/universaldiscovery/search.css'
                - 'bundles/ezplatformui/css/views/universaldiscovery/selected.css'
                - 'bundles/ezplatformui/css/views/universaldiscovery/confirmedlist.css'
                - 'bundles/ezplatformui/css/views/tree.css'
                - 'bundles/ezplatformui/css/views/loginform.css'
                - 'bundles/ezplatformui/css/views/contentedit.css'
                - 'bundles/ezplatformui/css/views/locationview.css'
                - 'bundles/ezplatformui/css/views/subitemlist.css'
                - 'bundles/ezplatformui/css/views/rawcontent.css'
                - 'bundles/ezplatformui/css/views/languageswitcher.css'
                - 'bundles/ezplatformui/css/views/tabs/details.css'
                - 'bundles/ezplatformui/css/views/tabs/relations.css'
                - 'bundles/ezplatformui/css/views/tabs/locations.css'
                - 'bundles/ezplatformui/css/views/field.css'
                - 'bundles/ezplatformui/css/views/fields/view/user.css'
                - 'bundles/ezplatformui/css/views/fields/view/author.css'
                - 'bundles/ezplatformui/css/views/fields/view/maplocation.css'
                - 'bundles/ezplatformui/css/views/fields/view/selection.css'
                - 'bundles/ezplatformui/css/views/fields/view/keyword.css'
                - 'bundles/ezplatformui/css/views/fields/view/country.css'
                - 'bundles/ezplatformui/css/views/fields/view/media.css'
                - 'bundles/ezplatformui/css/views/fields/view/richtext.css'
                - 'bundles/ezplatformui/css/views/contenteditform.css'
                - 'bundles/ezplatformui/css/views/bar.css'
                - 'bundles/ezplatformui/css/views/discoverybar.css'
                - 'bundles/ezplatformui/css/views/contenttypeselector.css'
                - 'bundles/ezplatformui/css/views/actions/tree.css'
                - 'bundles/ezplatformui/css/views/actions/button.css'
                - 'bundles/ezplatformui/css/views/actions/preview.css'
                - 'bundles/ezplatformui/css/views/actions/create-content.css'
                - 'bundles/ezplatformui/css/views/actions/translate.css'
                - 'bundles/ezplatformui/css/views/editpreview.css'
                - 'bundles/ezplatformui/css/views/fieldedit.css'
                - 'bundles/ezplatformui/css/views/error.css'
                - 'bundles/ezplatformui/css/views/asynchronous.css'
                - 'bundles/ezplatformui/css/views/dashboard.css'
                - 'bundles/ezplatformui/css/views/studiopresentation.css'
                - 'bundles/ezplatformui/css/views/studiopluspresentation.css'
                - 'bundles/ezplatformui/css/views/fields/edit/checkbox.css'
                - 'bundles/ezplatformui/css/views/fields/edit/country.css'
                - 'bundles/ezplatformui/css/views/fields/edit/textline.css'
                - 'bundles/ezplatformui/css/views/fields/edit/keyword.css'
                - 'bundles/ezplatformui/css/views/fields/edit/textblock.css'
                - 'bundles/ezplatformui/css/views/fields/edit/xmltext.css'
                - 'bundles/ezplatformui/css/views/fields/edit/emailaddress.css'
                - 'bundles/ezplatformui/css/views/fields/edit/url.css'
                - 'bundles/ezplatformui/css/views/fields/edit/float.css'
                - 'bundles/ezplatformui/css/views/fields/edit/integer.css'
                - 'bundles/ezplatformui/css/views/fields/edit/maplocation.css'
                - 'bundles/ezplatformui/css/views/fields/edit/author.css'
                - 'bundles/ezplatformui/css/views/fields/edit/binarybase.css'
                - 'bundles/ezplatformui/css/views/fields/edit/image.css'
                - 'bundles/ezplatformui/css/views/fields/edit/media.css'
                - 'bundles/ezplatformui/css/views/fields/edit/binaryfile.css'
                - 'bundles/ezplatformui/css/views/fields/edit/selection.css'
                - 'bundles/ezplatformui/css/views/fields/edit/time.css'
                - 'bundles/ezplatformui/css/views/fields/edit/date.css'
                - 'bundles/ezplatformui/css/views/fields/edit/dateandtime.css'
                - 'bundles/ezplatformui/css/views/fields/edit/relation.css'
                - 'bundles/ezplatformui/css/views/fields/edit/relationlist.css'
                - 'bundles/ezplatformui/css/views/fields/edit/richtext.css'
                - 'bundles/ezplatformui/css/views/fields/edit/isbn.css'
                - 'bundles/ezplatformui/css/views/fields/edit/user.css'
                - 'bundles/ezplatformui/css/modules/tabs.css'
                - 'bundles/ezplatformui/css/modules/page-header.css'
                - 'bundles/ezplatformui/css/modules/serverside-content.css'
                - 'bundles/ezplatformui/css/modules/selection-filter.css'
                - 'bundles/ezplatformui/css/modules/button.css'
                - 'bundles/ezplatformui/css/modules/table-data.css'
                - 'bundles/ezplatformui/css/modules/breadcrumbs.css'
                - 'bundles/ezplatformui/css/modules/yui-calendar.css'
                - 'bundles/ezplatformui/css/modules/pure-grid.css'
                - 'bundles/ezplatformui/css/alloyeditor/general.css'
                - 'bundles/ezplatformui/css/alloyeditor/content.css'
                - 'bundles/ezplatformui/css/alloyeditor/buttons/labeled-button.css'
            # theme stylesheets
                - 'bundles/ezplatformui/css/theme/app.css'
                - 'bundles/ezplatformui/css/theme/views/error.css'
                - 'bundles/ezplatformui/css/theme/views/loginform.css'
                - 'bundles/ezplatformui/css/theme/views/bar.css'
                - 'bundles/ezplatformui/css/theme/views/confirmbox.css'
                - 'bundles/ezplatformui/css/theme/views/languageselectionbox.css'
                - 'bundles/ezplatformui/css/theme/views/notificationhub.css'
                - 'bundles/ezplatformui/css/theme/views/notification.css'
                - 'bundles/ezplatformui/css/theme/views/universaldiscovery.css'
                - 'bundles/ezplatformui/css/theme/views/universaldiscovery/browse.css'
                - 'bundles/ezplatformui/css/theme/views/universaldiscovery/search.css'
                - 'bundles/ezplatformui/css/theme/views/universaldiscovery/selected.css'
                - 'bundles/ezplatformui/css/theme/views/universaldiscovery/confirmedlist.css'
                - 'bundles/ezplatformui/css/theme/views/tree.css'
                - 'bundles/ezplatformui/css/theme/views/discoverybar.css'
                - 'bundles/ezplatformui/css/theme/views/contenttypeselector.css'
                - 'bundles/ezplatformui/css/theme/views/actions/tree.css'
                - 'bundles/ezplatformui/css/theme/views/actions/button.css'
                - 'bundles/ezplatformui/css/theme/views/actions/preview.css'
                - 'bundles/ezplatformui/css/theme/views/actions/create-content.css'
                - 'bundles/ezplatformui/css/theme/views/actions/translate.css'
                - 'bundles/ezplatformui/css/theme/views/dashboard.css'
                - 'bundles/ezplatformui/css/theme/views/studiopresentation.css'
                - 'bundles/ezplatformui/css/theme/views/studiopluspresentation.css'
                - 'bundles/ezplatformui/css/theme/views/serverside.css'
                - 'bundles/ezplatformui/css/theme/views/navigationhub.css'
                - 'bundles/ezplatformui/css/theme/views/locationview.css'
                - 'bundles/ezplatformui/css/theme/views/subitemlist.css'
                - 'bundles/ezplatformui/css/theme/views/rawcontent.css'
                - 'bundles/ezplatformui/css/theme/views/languageswitcher.css'
                - 'bundles/ezplatformui/css/theme/views/asynchronous.css'
                - 'bundles/ezplatformui/css/theme/views/tabs/details.css'
                - 'bundles/ezplatformui/css/theme/views/tabs/relations.css'
                - 'bundles/ezplatformui/css/theme/views/tabs/locations.css'
                - 'bundles/ezplatformui/css/theme/views/field.css'
                - 'bundles/ezplatformui/css/theme/views/fields/view/url.css'
                - 'bundles/ezplatformui/css/theme/views/fields/view/binaryfile.css'
                - 'bundles/ezplatformui/css/theme/views/fields/view/maplocation.css'
                - 'bundles/ezplatformui/css/theme/views/fields/view/xmltext.css'
                - 'bundles/ezplatformui/css/theme/views/fields/view/media.css'
                - 'bundles/ezplatformui/css/theme/views/fields/view/richtext.css'
                - 'bundles/ezplatformui/css/theme/views/contentedit.css'
                - 'bundles/ezplatformui/css/theme/views/contenteditform.css'
                - 'bundles/ezplatformui/css/theme/views/editpreview.css'
                - 'bundles/ezplatformui/css/theme/views/fieldedit.css'
                - 'bundles/ezplatformui/css/theme/views/fields/view/keyword.css'
                - 'bundles/ezplatformui/css/theme/views/fields/view/country.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/maplocation.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/author.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/selection.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/binarybase.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/image.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/media.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/binaryfile.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/date.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/dateandtime.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/relation.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/relationlist.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/country.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/richtext.css'
                - 'bundles/ezplatformui/css/theme/views/fields/edit/user.css'
                - 'bundles/ezplatformui/css/theme/modules/icons.css'
                - 'bundles/ezplatformui/css/theme/modules/tabs.css'
                - 'bundles/ezplatformui/css/theme/modules/page-header.css'
                - 'bundles/ezplatformui/css/theme/modules/serverside-content.css'
                - 'bundles/ezplatformui/css/theme/modules/selection-filter.css'
                - 'bundles/ezplatformui/css/theme/modules/button.css'
                - 'bundles/ezplatformui/css/theme/modules/selection-table.css'
                - 'bundles/ezplatformui/css/theme/modules/breadcrumbs.css'
                - 'bundles/ezplatformui/css/theme/modules/yui-calendar.css'
                - 'bundles/ezplatformui/css/theme/alloyeditor/general.css'
                - 'bundles/ezplatformui/css/theme/alloyeditor/content.css'
                - 'bundles/ezplatformui/css/theme/alloyeditor/buttons/labeled-button.css'
                - 'bundles/ezplatformui/css/theme/alloyeditor/buttons/blockremove.css'
                - 'bundles/ezplatformui/css/theme/alloyeditor/buttons/embedhref.css'
