parameters:
    ez_platformui.default.yui: {}
    ez_platformui.default.yui.filter: "min"
    ez_platformui.default.yui.combine: true
    ez_platformui.default.yui.build_dir: /bundles/ezplatformuiassets/vendors/yui3/build/
    ez_platformui.default.yui.modules: []
    # Requirements for each YUI module can be found after compilation under:
    # ez_platformui.<scope>.yui.modules.<module_name>.requires
    # For reverse requirements:
    # ez_platformui.<scope>.yui.modules.<module_name>.dependencyOf
    # Path:
    # ez_platformui.<scope>.yui.modules.<module_name>.path
    # Type ('js' or 'template')
    # ez_platformui.<scope>.yui.modules.<module_name>.type
    ez_platformui.default.css.files: []
