
shell:
    pattern: /shell
    defaults: { _controller: eZPlatformUIBundle:PlatformUI:shell }

template_yui_module:
    path: /tpl/handlebars/{module}.js
    defaults:
        _controller: ezsystems.platformui.controller.template:wrapTemplateAction
        _format: js
    requirements:
        _method: GET

admin_dashboard:
    pattern: /pjax/dashboard
    defaults:
        _controller: ezsystems.platformui.controller.dashboard:dashboardAction
    methods: [GET]

admin_systeminfo:
    pattern: /pjax/systeminfo
    defaults:
        _controller: ezsystems.platformui.controller.systeminfo:infoAction
    methods: [GET]

admin_phpinfo:
    pattern: /systeminfo/phpinfo
    defaults:
        _controller: ezsystems.platformui.controller.systeminfo:phpinfoAction
    methods: [GET]

admin_sectionlist:
    path: /pjax/section/list
    defaults:
        _controller: ezsystems.platformui.controller.section:listAction
    methods: [GET]

admin_sectionview:
    path: /pjax/section/view/{sectionId}
    defaults:
        _controller: ezsystems.platformui.controller.section:viewAction
    methods: [GET]
    requirements:
        sectionId: \d+

admin_accessdenied:
    path: /pjax/accessdenied
    defaults:
        _controller: ezsystems.platformui.controller.pjax:accessDeniedAction

admin_sectioncreate:
    path: /pjax/section/create
    defaults:
        _controller: ezsystems.platformui.controller.section:createAction

admin_sectionedit:
    path: /pjax/section/edit/{sectionId}
    defaults:
        _controller: ezsystems.platformui.controller.section:editAction
    requirements:
            sectionId: \d+
