parameters:
    yui:
        modules:
            ez-capi:
                path: vendors/ez-js-rest-client/dist/CAPI.js
            ez-editorialapp:
                requires:
                    - 'app'
                    - 'app-transitions'
                    - 'node-screen'
                    - 'json'
                    - 'parallel'
                    - 'ez-capi'
                    - 'ez-contenteditviewloader'
                    - 'ez-contenteditview'
                    - 'ez-contenteditformview'
                    - 'ez-editactionbarview'
                    - 'ez-editpreviewview'
                    - 'ez-textline-editview'
                    - 'ez-emailaddress-editview'
                    - 'ez-float-editview'
                    - 'ez-integer-editview'
                    - 'ez-errorview'
                    - 'ez-buttonactionview'
                    - 'ez-previewactionview'
                path: js/apps/ez-editorialapp.js
            ez-viewloader:
                requires: ['base']
                path: js/views/loaders/ez-viewloader.js
            ez-contenteditviewloader:
                requires: ['parallel', 'ez-viewloader', 'ez-contentmodel', 'ez-locationmodel', 'ez-contenttypemodel', 'ez-usermodel']
                path: js/views/loaders/ez-contenteditviewloader.js
            ez-templatebasedview:
                requires: ['view', 'handlebars']
                path: js/views/ez-templatebasedview.js
            ez-contenteditview:
                requires: ['ez-templatebasedview', 'ez-contenteditformview', 'ez-editactionbarview', 'transition', 'event-tap']
                path: js/views/ez-contenteditview.js
            ez-contenteditformview:
                requires: ['ez-templatebasedview', 'transition', 'event-tap']
                path: js/views/ez-contenteditformview.js
            ez-errorview:
                requires: ['ez-templatebasedview', 'transition', 'event-tap']
                path: js/views/ez-errorview.js
            ez-fieldeditview:
                requires: ['ez-templatebasedview']
                path: js/views/ez-fieldeditview.js
            ez-textline-editview:
                requires: ['ez-fieldeditview', 'event-valuechange']
                path: js/views/fields/ez-textline-editview.js
            ez-emailaddress-editview:
                requires: ['ez-fieldeditview', 'event-valuechange']
                path: js/views/fields/ez-emailaddress-editview.js
            ez-float-editview:
                requires: ['ez-fieldeditview', 'event-valuechange']
                path: js/views/fields/ez-float-editview.js
            ez-integer-editview:
                requires: ['ez-fieldeditview', 'event-valuechange']
                path: js/views/fields/ez-integer-editview.js
            ez-restmodel:
                requires: ['model']
                path: js/models/ez-restmodel.js
            ez-contentmodel:
                requires: ['ez-restmodel']
                path: js/models/ez-contentmodel.js
            ez-locationmodel:
                requires: ['ez-restmodel']
                path: js/models/ez-locationmodel.js
            ez-usermodel:
                requires: ['ez-restmodel']
                path: js/models/ez-usermodel.js
            ez-contenttypemodel:
                requires: ['ez-restmodel']
                path: js/models/ez-contenttypemodel.js
            ez-editactionbarview:
                requires: ['ez-templatebasedview', 'ez-buttonactionview', 'ez-previewactionview', 'transition', 'event-tap', 'event-resize']
                path: js/views/ez-editactionbarview.js
            ez-buttonactionview:
                requires: ['ez-templatebasedview']
                path: js/views/actions/ez-buttonactionview.js
            ez-previewactionview:
                requires: ['ez-buttonactionview', 'ez-editpreviewview']
                path: js/views/actions/ez-previewactionview.js
            ez-editpreviewview:
                requires: ['ez-templatebasedview', 'transition', 'event-tap']
                path: js/views/ez-editpreviewview.js
        filter: min
